### PR TITLE
FIxed: Largest items in inbox size in NaN

### LINKED ISSUE #182: Largest items in inbox - Size is NaN
Under the **What are the largest items in your inbox?** section, the size for every email is being displayed as `NaN MB`.

inbox0

### PR DESCRIPTION
**Pull request by madhav-relish**
### Description
This PR fixes a feature to calculate the total size of email attachments and display it in the UI.

### Changes
- Added a function to calculate the total size of attachments.
- Updated the UI to display the total size of attachments in MB.

Screenshot 2024-07-05 100212

### Related Issue
Fixes #182 

## Summary by CodeRabbit

- **New Features**
  - Enhanced email statistics by adding a feature to calculate and display the total size of attachments for each email.

### CODE REVIEW

File: apps/web/app/(app)/stats/LargestEmails.tsx [hunk 1]
```diff
@@ -36,6 +37,16 @@ export function LargestEmails(props: { refreshInterval: number }) {
...
+  // Function to calculte total attachement size
+  const calculateTotalAttachmentSize = (attachments?: Attachment[]): number => {
+    return (
+      attachments?.reduce(
+        (sum: number, attachment: Attachment) => sum + attachment.size,
+        0,
+      ) || 0
+    );
+  };
+
```
Comment (elie222) [inline apps/web/app/(app)/stats/LargestEmails.tsx]: Maybe use `sum` from lodash just because we use this in other places in the app anyway. And just easier to read a one liner over `reduce`.

**Review by elie222 — CHANGES_REQUESTED** [review]
Thanks. Been needing to get this fixed for a while now!

File: apps/web/app/(app)/stats/LargestEmails.tsx (hunk 1 above)
Comment (madhav-relish) [reply apps/web/app/(app)/stats/LargestEmails.tsx]: Done!

**Comment by elie222** [comment]
Thanks!!
