### PR TITLE
#230 : Unsubscribe automation

### LINKED ISSUE #230: Implement Automated Unsubscribe Feature
## Description
Develop a Playwright-based application that automatically navigates and completes unsubscribe processes for email subscriptions, using an LLM to interpret pages and guide actions.

## Objectives
1. Create a Playwright automation tool for unsubscribe flows
2. Integrate an LLM to analyze pages and determine actions
3. Handle various unsubscribe page layouts and processes
4. Integrate with the main Inbox Zero application

## Implementation Flow
1. User provides unsubscribe link
2. Playwright loads the page
3. LLM analyzes content and determines actions
4. Playwright executes actions
5. System confirms success or reports issues

## Key Components
1. Playwright Setup
2. LLM Integration
3. Action Execution
4. Error Handling and Reporting
5. Integration with Inbox Zero

## Potential Implementation

```typescript
import { generateObject } from 'ai';
import { z } from 'zod';
import { chromium } from 'playwright';

async function autoUnsubscribe(url: string) {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto(url);

  const pageContent = await page.content();

  const { object } = await generateObject({
    model: 'your-chosen-model',
    schema: z.object({
      actions: z.array(z.object({
        type: z.enum(['click', 'fill', 'select', 'submit']),
        selector: z.string(),
        value: z.string().optional(),
      })),
      confirmationIndicator: z.string(),
    }),
    prompt: `Analyze the HTML content and determine actions to unsubscribe. Provide a confirmation indicator.\n\n${pageContent}`,
  });

  for (const action of object.actions) {
    // Execute actions based on type
  }

  const confirmationElement = await page.$(object.confirmationIndicator);
  const success = !!confirmationElement;

  await browser.close();
  return success;
}
```

The app can be accessed using Fastify:

```ts
import fastify from 'fastify';
import { autoUnsubscribe } from './autoUnsubscribe'; // Import the function we created earlier

const server = fastify();

server.post<{
  Body: { url: string };
  Reply: { success: boolean; message: string };
}>('/unsubscribe', async (request, reply) => {
  const { url } = request.body;

  if (!url) {
    reply.code(400).send({ success: false, message: 'URL is required' });
    return;
  }

  try {
    const success = await autoUnsubscribe(url);

    if (success) {
      reply.send({ success: true, message: 'Successfully unsubscribed' });
    } else {
      reply.send({ success: false, message: 'Unsubscribe process completed, but confirmation not found' });
    }
  } catch (error) {
    console.error('Unsubscribe error:', error);
    reply.code(500).send({ success: false, message: 'Error during unsubscribe process' });
  }
});

const start = async () => {
  try {
    await server.listen({ port: 3001 });
    console.log('Server running on http://localhost:3001');
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

start();
```

## Next Steps
1. Set up a new app in the `apps` folder
2. Add Playwright
3. Integrate Vercel AI package and implement `generateObject`
4. Develop prompt and schema for page analysis
5. Implement action execution logic
6. Create API endpoint for Inbox Zero integration
7. Conduct testing and refinement

## Future Enhancements
- Support for login-required unsubscribes
- Complex unsubscribe processes
- CAPTCHAs and human verification
- Performance management

### PR DESCRIPTION
**Pull request by madhav-relish**
# Description

Develop a Playwright-based application that automatically navigates and completes unsubscribe processes for email subscriptions, using an LLM to interpret pages and guide actions.

## Changes

- Created a new `unsubscribe-automation` service
- Implemented `autoUnsubscribe` function using Playwright for web automation
- Added AI analysis of unsubscribe pages using Google's Generative AI
- Set up a Fastify server to expose the unsubscribe functionality as an API endpoint
- Implemented error handling and logging throughout the process
- Added CORS support for frontend integration

## New Files

- `src/main.ts`: Core logic for unsubscribe automation
- `src/server.ts`: Fastify server setup and API endpoint
- `package.json`: Project dependencies and scripts
- `tsconfig.json`: TypeScript configuration
- `.env`: Environment variables (not committed, added to .gitignore)

## Dependencies Added

- `playwright`: For web automation
- `@google/generative-ai`: For AI-powered page analysis
- `fastify`: For creating the API server
- `@fastify/cors`: For CORS support
- `zod`: For input validation
- `dotenv`: For environment variable management

## Next Steps

- Integrate this service with the main application
- Implement more robust error handling and retries
- Consider adding support for more complex unsubscribe flows (e.g., multi-step processes)
- Adding more LLM support like vercelAI

Fixes #230 

## Summary by CodeRabbit

- **New Features**
	- Introduced an automated unsubscribe service leveraging AI for email newsletter unsubscription.
	- Added a Fastify server to handle unsubscribe requests with validation.
	- Implemented a RESTful API endpoint for triggering unsubscribe actions.
	- Enhanced functionality with structured AI analysis and error handling for unsubscribe actions.

- **Configuration**
	- New environment variables added for Google AI services and CORS settings.
	- Created a new `package.json` file detailing project metadata and scripts.
	- Added TypeScript configuration for project compilation.

- **Documentation**
	- Provided comprehensive documentation for the Unsubscribe Automation Service, including installation and usage instructions.
	- Detailed API endpoints and troubleshooting guidance for users.

### CODE REVIEW

File: unsubscribe-automation/src/main.ts [hunk 1]
```diff
@@ -0,0 +1,199 @@
+import { chromium, Page } from "playwright";
+import { GoogleGenerativeAI } from "@google/generative-ai";
+import { z } from "zod";
+
+import dotenv from "dotenv";
+
+dotenv.config();
+
+const genAI = new GoogleGenerativeAI(process.env.GOOGLE_AI_API_KEY || "");
```
Comment (elie222) [inline unsubscribe-automation/src/main.ts]: Use vercel `ai` as this is what we use in the core app too.

Comment (elie222) [reply unsubscribe-automation/src/main.ts]: https://sdk.vercel.ai/docs/ai-sdk-core/overview

File: unsubscribe-automation/README.md [hunk 2]
```diff
@@ -0,0 +1,101 @@
+# Unsubscribe Automation Service
```
Comment (elie222) [inline unsubscribe-automation/README.md]: Move to `apps` folder. `web` is one app. `unsubscribe-automation` is another app.

File: unsubscribe-automation/README.md [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+- If you encounter any issues with Playwright, ensure that you have the necessary system dependencies installed. Refer to the [Playwright installation guide](https://playwright.dev/docs/intro#installation) for more information.
+- Check the console output for any error messages or logs that might indicate the cause of any issues.
+
+## Contributing
+
+Please read [CONTRIBUTING.md](CONTRIBUTING.md) for details on our code of conduct and the process for submitting pull requests.
+
+## License
+
+This project is licensed under the MIT License - see the [LICENSE.md](LICENSE.md) file for details.
```
Comment (elie222) [inline unsubscribe-automation/README.md]: Remove this. The project already has these that cover everything.

File: unsubscribe-automation/src/server.ts [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+
+const server = fastify();
+
+// Register CORS
+server.register(cors, {
+  origin: process.env.CORS_ORIGIN || "http://localhost:3000",
+  methods: ["GET", "POST"],
+});
+
+const UnsubscribeSchema = z.object({
```
Comment (elie222) [inline unsubscribe-automation/src/server.ts]: Start schemas with a lowercase letter. ie `UnsubscribeSchema`.
This is minor, but just keeps it consistent with the rest of the project. (I've seen other projects use the style you have here, but we don't)
Also zod docs, start with lowercase: https://zod.dev/?id=basic-usage

File: unsubscribe-automation/src/server.ts [hunk 5]
```diff
@@ -0,0 +1,54 @@
+import fastify from "fastify";
+import cors from "@fastify/cors";
+import { autoUnsubscribe } from "./main";
+import { z } from "zod";
+
+const server = fastify();
+
+// Register CORS
+server.register(cors, {
+  origin: process.env.CORS_ORIGIN || "http://localhost:3000",
```
Comment (elie222) [inline unsubscribe-automation/src/server.ts]: Can remove: `|| "http://localhost:3000",`
If you want to set it as an env var to be localhost:3000 you can.
In production this may not be set at all.

File: unsubscribe-automation/src/server.ts [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+      .status(500)
+      .send({ error: "An error occurred during the unsubscribe process" });
+  }
+});
+
+const start = async () => {
+  try {
+    const port = process.env.PORT ? parseInt(process.env.PORT) : 5000;
+    await server.listen({ port, host: "0.0.0.0" });
+    console.log(`Server is running on http://localhost:${port}`);
```
Comment (elie222) [inline unsubscribe-automation/src/server.ts]: it won't always be localhost. You can just log "started on port $port"

File: unsubscribe-automation/src/main.ts [hunk 7]
```diff
@@ -0,0 +1,199 @@
...
+    "button:has-text(/unsubscribe/i)",
+    "a:has-text(/unsubscribe/i)",
+    'input[type="submit"][value*="unsubscribe" i]',
+    ':text("unsubscribe")',
+  ];
+
+  for (const selector of unsubscribeSelectors) {
+    const element = page.locator(selector);
+    if ((await element.count()) > 0) {
+      await element.click({ timeout: 5000 }).catch(console.warn);
```
Comment (elie222) [inline unsubscribe-automation/src/main.ts]: prefer wrapping in try/catch for consistency

File: unsubscribe-automation/src/main.ts [hunk 8]
```diff
@@ -0,0 +1,199 @@
...
+  }
+}
+
+async function performFallbackUnsubscribe(page: Page) {
+  const unsubscribeSelectors = [
+    "button:has-text(/unsubscribe/i)",
+    "a:has-text(/unsubscribe/i)",
+    'input[type="submit"][value*="unsubscribe" i]',
+    ':text("unsubscribe")',
+  ];
```
Comment (elie222) [inline unsubscribe-automation/src/main.ts]: Potentially more robust solution provided by Claude:

```ts
import { Page, ElementHandle } from 'playwright';

async function performFallbackUnsubscribe(page: Page): Promise<boolean> {
  const unsubscribeKeywords = [
    'unsubscribe',  // English
    'désabonner',   // French
    'abbestellen',  // German
    'cancelar suscripción', // Spanish
    'annulla iscrizione',   // Italian
    '退订',  // Chinese (Simplified)
    '退訂',  // Chinese (Traditional)
    '退会',  // Japanese
    'отписаться', // Russian
    'se désabonner', // Alternative French
    'désinscription', // Another French alternative
    'abmelden',   // Alternative German
    'darse de baja', // Alternative Spanish
  ];

  const generateSelectors = (keyword: string) => [
    `button:has-text("${keyword}")`,
    `a:has-text("${keyword}")`,
    `input[type="submit"][value*="${keyword}" i]`,
    `:text("${keyword}")`,
    `[aria-label*="${keyword}" i]`,
    `[title*="${keyword}" i]`,
  ];

  const allSelectors = unsubscribeKeywords.flatMap(generateSelectors);

  for (const selector of allSelectors) {
    try {
      const elements = await page.$$(selector);
      if (elements.length > 0) {
        // Filter visible elements
        const visibleElements = await Promise.all(
          elements.map(async (el) => (await el.isVisible()) ? el : null)
        );
        const element = visibleElements.find((el) => el !== null) as ElementHandle<Element> | undefined;

        if (element) {
          await element.click({ timeout: 5000 });
          console.log(`Successfully clicked unsubscribe element: ${selector}`);
          return true;
        }
      }
    } catch (error) {
      console.warn(`Error trying to click ${selector}:`, error);
    }
  }

  console.log('No unsubscribe element found or clicked in fallback strategy');
  return false;
}
```

**And it's explanation in case you disagree with its reasoning:**

Here are the key improvements made to the function:

Return value: The function now returns a boolean indicating success or failure, which can be useful for error handling or flow control in the calling code.
Error handling: Each selector attempt is now wrapped in a try-catch block, allowing the function to continue trying other selectors if one fails.
Visibility check: The function now checks for element visibility before attempting to click, which can help avoid clicking on hidden elements.
Use of $$ instead of locator: This change allows for more precise element selection and easier handling of multiple matching elements.
Timeout handling: The click timeout is still set to 5000ms, but now it's handled more gracefully within the try-catch block.
TypeScript types: Added proper type annotations for better type safety and code clarity.
Flexibility: The selectors array is now easier to extend with additional selectors if needed.

These changes should make the function more robust and reliable for finding and clicking unsubscribe elements across various webpage structures. The function will try all selectors, handle errors gracefully, and only attempt to click visible elements.

File: unsubscribe-automation/src/main.ts [hunk 9]
```diff
@@ -0,0 +1,199 @@
...
+    }
+    await page
+      .waitForLoadState("networkidle", { timeout: 5000 })
+      .catch(() => {});
+  }
+}
+
+export async function autoUnsubscribe(url: string): Promise<boolean> {
+  // Remove headless: false if you don't want the browser popup to open
+  const browser = await chromium.launch({ headless: false });
```
Comment (elie222) [inline unsubscribe-automation/src/main.ts]: Can set this as an env var. In prod we will likely use headless: true. But it is easier in dev to see it headful mode.

**Review by elie222 — CHANGES_REQUESTED** [review]
Checked half of it and left comments.

File: unsubscribe-automation/src/main.ts (hunk 1 above)
Comment (madhav-relish) [reply unsubscribe-automation/src/main.ts]: Added google ai using vercel ai sdk

File: unsubscribe-automation/README.md (hunk 2 above)
Comment (madhav-relish) [reply unsubscribe-automation/README.md]: Moved

File: unsubscribe-automation/README.md (hunk 3 above)
Comment (madhav-relish) [reply unsubscribe-automation/README.md]: Removed

File: unsubscribe-automation/src/server.ts (hunk 4 above)
Comment (madhav-relish) [reply unsubscribe-automation/src/server.ts]: Done

File: unsubscribe-automation/src/server.ts (hunk 5 above)
Comment (madhav-relish) [reply unsubscribe-automation/src/server.ts]: Done

File: unsubscribe-automation/src/main.ts (hunk 7 above)
Comment (madhav-relish) [reply unsubscribe-automation/src/main.ts]: Added try catch block

File: unsubscribe-automation/src/main.ts (hunk 8 above)
Comment (madhav-relish) [reply unsubscribe-automation/src/main.ts]: Done, need to add support for more complex unsubscribe pages like 

> select reasons for unsubscribing

File: unsubscribe-automation/src/main.ts (hunk 9 above)
Comment (madhav-relish) [reply unsubscribe-automation/src/main.ts]: Added an env variable

**Comment by elie222** [comment]
From a quick overview it's looking good! I'm going to test later today!

**Comment by elie222** [comment]
@madhav-relish I'm still going through this but looking good so far. Nice touch with the screenshot for errors

**Comment by elie222** [comment]
@madhav-relish thanks for the PR! Most of the changes I made were just Cursor going over each section of code.

One potentially big improvement would be to try click the button without using AI at all, with something like this:

```ts
await page.getByText('Unsubscribe').click()
```

And then for the different variations of this for different text that's common in unsub flows / different languages.

The next step for this would be to integrate it with the core app.
I think when the user clicks unsubscribe we could just do it for them, and then if we fail, we could just open a new tab for the user to do it themselves.
