### PR TITLE
Fix Loading on Delete

### LINKED ISSUE #913: No Loading Indicator & Modal Not Closing After Deleting a Rule
**Description**
When deleting a rule in the Rules section, the UI does not provide any visual feedback. There’s no loading spinner or progress indicator, and the rule dialog remains open even after the rule has been successfully deleted.

**Steps to Reproduce**
1. Click on any rule. 
2. When the dialog open click on delete.
3. Observe there is no loading indicator. 
4. Even the toast shows deleted the dialog does not close.

https://github.com/user-attachments/assets/7f08f152-994d-4249-b81c-0f6965c5793d

### PR DESCRIPTION
**Pull request by ppranay20**
Fixes #913 

---

### 📌 Description
This PR adds loading spinner when deleting a rule.

### ✅ Changes Included
* Added a loading state while deleting a rule.
* Disabled the Save button during rule deletion to prevent invalid actions or errors.
* Disabled the Delete button while saving a rule.
* Automatically closed the dialog once a rule has been successfully deleted.

## Summary by CodeRabbit

* **Bug Fixes**
  * Added loading state feedback during rule deletion to indicate operation in progress.
  * Save and delete buttons are now properly disabled during operations to prevent duplicate submissions.
  * Ensures proper navigation after successful rule deletion.

### CODE REVIEW

File: apps/web/app/(app)/[emailAccountId]/assistant/RuleForm.tsx [hunk 1]
```diff
@@ -849,7 +860,7 @@ export function RuleForm({
           )}
 
           {rule.id ? (
-            <Button type="submit" loading={isSubmitting}>
+            <Button type="submit" loading={isSubmitting} disabled={isDeleting}>
```
Comment (elie222) [inline apps/web/app/(app)/[emailAccountId]/assistant/RuleForm.tsx:863]: `loading={isSubmitting || isDeleting}` would work. and show loading. it will auto set disabled

Comment (elie222) [reply apps/web/app/(app)/[emailAccountId]/assistant/RuleForm.tsx:863]: You don't need disabled if loading is set (if you look in the Button code)

Comment (ppranay20) [reply apps/web/app/(app)/[emailAccountId]/assistant/RuleForm.tsx:863]: In that case it will add a spinner in the save button too when deleting a rule.

Comment (elie222) [reply apps/web/app/(app)/[emailAccountId]/assistant/RuleForm.tsx:863]: ah my bad. it's a different button
